Adding Travis CI to project
wolox-training/gb-rails pull request #4
Opened 2017-08-30 18:03 UTC by gabybrow

## Summary
- Adding Travis configuration to project

## Trello Card
https://trello.com/c/ruud0m6N/13-configurar-travisci

2017-08-30 21:14 UTC, Dinuuu approved these changes

2017-08-30 21:14 UTC, Dinuuu commented on .travis.yml
> +  bundler: true
remember to add the new line at the end of the files, you can configure your IDE to do it for you automatically

2017-08-30 21:14 UTC, Dinuuu commented on config/database.travis.yml
> +  username: rails-bootstrap
I would change this username and password by wbooks (here and in the .travis.yml file)

2017-08-30 21:14 UTC, Dinuuu commented on config/database.travis.yml
> +  password: rails-bootstrap
new line missing

2017-08-30 21:14 UTC, Dinuuu commented on .travis.yml
> +  - bundle exec rspec spec -fd
You don't need rspec yet, you can remove this line

2017-08-30 21:14 UTC, Dinuuu commented on Gemfile
> +group :test do
Mmmm there are a lot of gems that you don't need for this task ( I suppose you added them because travis was failing because of rspec command)

2017-08-30 21:34 UTC, Dinuuu requested changes
I miss clicked into approve :P

2017-08-31 15:39 UTC, Dinuuu approved these changes
Add a new line at the end of `.travis.yml` and `config/database.travis.yml` and merge it 👍

2017-08-31 15:51 UTC, gabybrow commented
I've already added in both files. I don't know why github is not showing them in the PR
![image](https://user-images.githubusercontent.com/11915362/29932582-0d6ca65e-8e4b-11e7-9927-a493b89dfd65.png)

2017-08-31 15:51 UTC, merged